/* Bump the cache stamp.  node tools/stamp.mjs
   Rewrites every ?v= in index.html AND version.txt from one value.
   version.txt on its own is a lie: the ?v= stamps are the real cache key. */
import { readFileSync, writeFileSync, existsSync, copyFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const STAMP = String(Math.floor(Date.now() / 1000));

/* ---------- the shared progress files ----------
   labs-shared/labs.json is the single register of labs — one place for each lab's question
   count, the shelf it sits behind, and the localStorage key it keeps progress under (which is
   NOT always <id>.v2). labs-shared/progress.js is the only code that knows how to read a
   lab's record, so this hub never has to know a lab's internals. Both are copied in here, so
   the published site is self-contained: adding a lab means editing labs.json and rebuilding. */
function findShared(from) {
  let dir = from;
  for (let i = 0; i < 8; i++) {
    if (existsSync(resolve(dir, 'labs-shared/labs.json'))) return resolve(dir, 'labs-shared');
    const up = resolve(dir, '..'); if (up === dir) break; dir = up;
  }
  return null;
}
const SHARED = findShared(REPO);
if (SHARED) {
  mkdirSync(resolve(REPO, 'js/data'), { recursive: true });
  copyFileSync(resolve(SHARED, 'labs.json'), resolve(REPO, 'js/data/labs.json'));
  const reg = readFileSync(resolve(SHARED, 'labs.json'), 'utf8');
  writeFileSync(resolve(REPO, 'js/data/labs.js'),
    '/* GENERATED by tools/stamp.mjs from labs-shared/labs.json — do not edit. */\n' +
    'window.LABS_REGISTER = ' + reg.trim() + ';\n');
  copyFileSync(resolve(SHARED, 'progress.js'), resolve(REPO, 'js/progress.js'));
  console.log('  shared        labs.json + progress.js copied in');
} else {
  console.error('  labs-shared/ not found above ' + REPO + ' — progress files not refreshed');
}
const idx = resolve(REPO, 'index.html');
const html = readFileSync(idx, 'utf8');
const n = (html.match(/\?v=\d+/g) || []).length;
if (!n) { console.error('index.html carries no ?v= stamps'); process.exit(1); }
writeFileSync(idx, html.replace(/\?v=\d+/g, '?v=' + STAMP));
writeFileSync(resolve(REPO, 'version.txt'), STAMP + '\n');
console.log('stamped ' + n + ' assets and version.txt with ' + STAMP);
